on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3'
      - run: pip install gigalixir --ignore-installed six
      - run: gigalixir login -y -e '${{ secrets.GIGALIXIR_EMAIL }}' -p '${{ secrets.GIGALIXIR_PASSWORD }}'
      - run: gigalixir git:remote ${{ secrets.GIGALIXIR_APPNAME }}
      - run: 'git -c http.extraheader="GIGALIXIR-HOT: true" push gigalixir'
